In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error

Load the Dataset

In [2]:
df = pd.read_csv("data/taxi_pickups_area.csv")
df.shape

(8064, 79)

Convert Trip Start Timestamp to datetime object

In [3]:
areas = [c for c in df.columns.to_list() if c != 'Trip Start Timestamp']
df['Trip Start Timestamp'] = pd.to_datetime(df['Trip Start Timestamp'])

Train validation split

In [4]:
train_size = int(len(df) * 0.8)

train = df[:train_size]
val = df[train_size:]

train.shape

(6451, 79)

In [5]:
val.shape

(1613, 79)

Time Series Preprocessing

Check Missing values and time frequency

In [6]:
# missing = train[train.isnan()].count()
train[train.isna()].count()

Trip Start Timestamp        0
Pickup Community Area_0     0
Pickup Community Area_1     0
Pickup Community Area_2     0
Pickup Community Area_3     0
                           ..
Pickup Community Area_73    0
Pickup Community Area_74    0
Pickup Community Area_75    0
Pickup Community Area_76    0
Pickup Community Area_77    0
Length: 79, dtype: int64

no missing values detected

Check time Frequency

In [7]:
pd.infer_freq(train[train.columns[0]])

'15min'

Time Frequency constant 15-min interval

Handle anomalies with STL Decomposition for each area

In [27]:
from statsmodels.tsa.seasonal import STL

cleaned_train = train.copy()

# def detect_anomalies(serie, robust=True, period=672, threshold=3.0): # an be used!

#     stl = STL(serie, robust=robust, period=period)
#     result = stl.fit()
#     resid = result.resid

#     # Robust center/scale — mean/std get skewed by the very anomalies we want to find
#     median = resid.median()
#     mad = np.median(np.abs(resid - median))
#     mad_std = mad * 1.4826 if mad != 0 else resid.std()  # fallback if MAD is 0

#     lower = median - (threshold * mad_std)
#     upper = median + (threshold * mad_std)
#     return serie[(resid < lower) | (resid > upper)]

def detect_anomalies(serie, robust=True, period=672):

    stl = STL(serie, robust=robust, period=period)

    result = stl.fit()

    resid =  result.resid

    resid_m = resid.mean()
    resid_dv = resid.std()

    lower = resid_m - (3 * resid_dv) 
    upper = resid_m + (3 * resid_dv)

    return serie[(resid < lower) | (resid > upper)]


for area in areas:
    
    serie = train[area]

    anomalies = detect_anomalies(serie)
    
    serie.loc[anomalies.index] = np.nan

    serie = serie.interpolate(
        method="linear",
        limit_direction="both"
    )

    cleaned_train[area] = serie

save cleaned train time series

In [28]:
import joblib
joblib.dump(cleaned_train, "cleaned_train.pkl")

['cleaned_train.pkl']

Load Cleaned train set

In [5]:
import joblib

cleaned_train = joblib.load("cleaned_train.pkl")
# print(train["Pickup Community Area_25"].hasnans)

In [ ]:
Log Transformation

In [6]:
transformed_train = cleaned_train

for area in areas:
    transformed_train[area] = np.log1p(transformed_train[area])

Check and make time series stationary for each Area with Augmented Dickey fuller test and differencing

In [8]:
from statsmodels.tsa.stattools import adfuller
# import matplotlib.pyplot as plt


def check_stationarity(serie, significance_level=0.05):

    # Drop missing values caused by differencing
    # clean_serie = pd.Series(serie).dropna()
    
    # Handle edge case: empty series or zero variance
    # if len(clserie) < 10 or serie.nunique() <= 1:
    #     return False

    result = adfuller(serie, autolag='AIC')
    p_value = result[1]

    return p_value < significance_level


def make_stationary_diff(serie, max_diff=3, significance_level=0.05):

    current_serie = pd.Series(serie).copy()
    diff_count = 0

    while diff_count < max_diff:
        if check_stationarity(current_serie, significance_level):
            break
            
        current_serie = current_serie.diff().dropna()
        diff_count += 1

    return current_serie, diff_count


for area in areas:
    serie, diff_count = make_stationary_diff(transformed_train[area])
    transformed_train[area] = serie

transformed_train.isna().sum()

ValueError: Invalid input, x is constant

Fit Naive averages using Global average for each Area

In [10]:
global_averages = transformed_train[areas].mean()
global_averages

Pickup Community Area_0     1.798926
Pickup Community Area_1     0.628776
Pickup Community Area_2     0.616233
Pickup Community Area_3     1.134126
Pickup Community Area_4     0.529569
                              ...
Pickup Community Area_73    0.068246
Pickup Community Area_74    0.000000
Pickup Community Area_75    0.030954
Pickup Community Area_76    2.921165
Pickup Community Area_77    0.991413
Length: 78, dtype: float64

Forecast each Area

In [11]:
forecast = pd.Series(index=areas)
for area in areas:
    forecast[area] = np.expm1(global_averages[area])

forecast

Pickup Community Area_0      5.043151
Pickup Community Area_1      0.875314
Pickup Community Area_2      0.851938
Pickup Community Area_3      2.108455
Pickup Community Area_4      0.698201
                              ...
Pickup Community Area_73     0.070629
Pickup Community Area_74     0.000000
Pickup Community Area_75     0.031438
Pickup Community Area_76    17.562896
Pickup Community Area_77     1.695041
Length: 78, dtype: float64

Compute Mean Absolute Error using validation

In [12]:

all_mea = []
for area in areas:
    area_pred = np.ones(len(val)) * forecast[area]
    mae = mean_absolute_error(area_pred, val[area])
    all_mea.append(mae)

average_mae = np.array(all_mea).mean()
print(f"average of all area mean absolute error : {average_mae}")

average of all area mean absolute error : 1.3989638609718165

Load Taxi submission Dataset

In [19]:
sub_df = pd.read_csv("data/taxi_submission_file.csv")

Forecast with naive averages and save

In [14]:
sub_pred = pd.DataFrame(columns=sub_df.columns)
sub_pred['Trip Start Timestamp'] = sub_df['Trip Start Timestamp']

for area in areas:
    area_pred = np.ones(len(sub_df)) * forecast[area]
    sub_pred[area] = np.floor(area_pred)


sub_pred

,Trip Start Timestamp,Pickup Community Area_0,Pickup Community Area_1,Pickup Community Area_2,Pickup Community Area_3,Pickup Community Area_4,Pickup Community Area_5,Pickup Community Area_6,Pickup Community Area_7,Pickup Community Area_8,...,Pickup Community Area_68,Pickup Community Area_69,Pickup Community Area_70,Pickup Community Area_71,Pickup Community Area_72,Pickup Community Area_73,Pickup Community Area_74,Pickup Community Area_75,Pickup Community Area_76,Pickup Community Area_77
0,2019-06-24 00:00:00,5.0,0.0,0.0,2.0,0.0,0.0,7.0,4.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,1.0
1,2019-06-24 00:15:00,5.0,0.0,0.0,2.0,0.0,0.0,7.0,4.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,1.0
2,2019-06-24 00:30:00,5.0,0.0,0.0,2.0,0.0,0.0,7.0,4.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,1.0
3,2019-06-24 00:45:00,5.0,0.0,0.0,2.0,0.0,0.0,7.0,4.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,1.0
4,2019-06-24 01:00:00,5.0,0.0,0.0,2.0,0.0,0.0,7.0,4.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,2019-06-30 22:45:00,5.0,0.0,0.0,2.0,0.0,0.0,7.0,4.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,1.0
668,2019-06-30 23:00:00,5.0,0.0,0.0,2.0,0.0,0.0,7.0,4.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,1.0
669,2019-06-30 23:15:00,5.0,0.0,0.0,2.0,0.0,0.0,7.0,4.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,1.0
670,2019-06-30 23:30:00,5.0,0.0,0.0,2.0,0.0,0.0,7.0,4.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,1.0
671,2019-06-30 23:45:00,5.0,0.0,0.0,2.0,0.0,0.0,7.0,4.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,1.0

Fit Simple Moving Averages

In [15]:
window = 10
sma_mae = []
sma_series = pd.Series(index=areas)
for area in areas:

    avg_window = transformed_train[area].tail(window).mean() # Fit using scaled values


    inversed_avg = np.expm1(avg_window)
    sma_series[area] = inversed_avg # hold the inversed forecast for each area
    forecast = np.ones(len(val)) * inversed_avg # just create val size of the sca
    sma_mae.append(mean_absolute_error(forecast, val[area]))

average_mae = np.array(sma_mae).mean()
print(f"average mean absolute error :{average_mae}")

average mean absolute error :0.8337175520198017

In [16]:
sub_pred = pd.DataFrame(columns=sub_df.columns)
sub_pred['Trip Start Timestamp'] = sub_df['Trip Start Timestamp']

for area in areas:
    area_pred = np.ones(len(sub_df)) * sma_series[area]
    sub_pred[area] = area_pred

sub_pred

,Trip Start Timestamp,Pickup Community Area_0,Pickup Community Area_1,Pickup Community Area_2,Pickup Community Area_3,Pickup Community Area_4,Pickup Community Area_5,Pickup Community Area_6,Pickup Community Area_7,Pickup Community Area_8,...,Pickup Community Area_68,Pickup Community Area_69,Pickup Community Area_70,Pickup Community Area_71,Pickup Community Area_72,Pickup Community Area_73,Pickup Community Area_74,Pickup Community Area_75,Pickup Community Area_76,Pickup Community Area_77
0,2019-06-24 00:00:00,0.966307,0.196231,0.0,0.390389,0.071773,0.0,0.578437,0.597138,4.983121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.578437,0.148698
1,2019-06-24 00:15:00,0.966307,0.196231,0.0,0.390389,0.071773,0.0,0.578437,0.597138,4.983121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.578437,0.148698
2,2019-06-24 00:30:00,0.966307,0.196231,0.0,0.390389,0.071773,0.0,0.578437,0.597138,4.983121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.578437,0.148698
3,2019-06-24 00:45:00,0.966307,0.196231,0.0,0.390389,0.071773,0.0,0.578437,0.597138,4.983121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.578437,0.148698
4,2019-06-24 01:00:00,0.966307,0.196231,0.0,0.390389,0.071773,0.0,0.578437,0.597138,4.983121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.578437,0.148698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,2019-06-30 22:45:00,0.966307,0.196231,0.0,0.390389,0.071773,0.0,0.578437,0.597138,4.983121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.578437,0.148698
668,2019-06-30 23:00:00,0.966307,0.196231,0.0,0.390389,0.071773,0.0,0.578437,0.597138,4.983121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.578437,0.148698
669,2019-06-30 23:15:00,0.966307,0.196231,0.0,0.390389,0.071773,0.0,0.578437,0.597138,4.983121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.578437,0.148698
670,2019-06-30 23:30:00,0.966307,0.196231,0.0,0.390389,0.071773,0.0,0.578437,0.597138,4.983121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.578437,0.148698
671,2019-06-30 23:45:00,0.966307,0.196231,0.0,0.390389,0.071773,0.0,0.578437,0.597138,4.983121,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.578437,0.148698

Fit Moving Averages using different window slice

In [17]:

window = 48
sma_mae = []
sma_series = pd.Series(index=areas)
for area in areas:

    avg_window = transformed_train[area].tail(window).mean() # Fit using scaled values


    inversed_avg = np.expm1(avg_window)
    sma_series[area] = inversed_avg # hold the inversed forecast for each area
    forecast = np.ones(len(val)) * inversed_avg # just create val size of the sca
    sma_mae.append(mean_absolute_error(forecast, val[area]))

average_mae = np.array(sma_mae).mean()
print(f"average mean absolute error :{average_mae}")

average mean absolute error :0.630961661042094

In [18]:
sub_pred = pd.DataFrame(columns=sub_df.columns)
sub_pred['Trip Start Timestamp'] = sub_df['Trip Start Timestamp']

for area in areas:
    area_pred = np.ones(len(sub_df)) * sma_series[area]
    sub_pred[area] = np.floor(area_pred)

sub_pred

,Trip Start Timestamp,Pickup Community Area_0,Pickup Community Area_1,Pickup Community Area_2,Pickup Community Area_3,Pickup Community Area_4,Pickup Community Area_5,Pickup Community Area_6,Pickup Community Area_7,Pickup Community Area_8,...,Pickup Community Area_68,Pickup Community Area_69,Pickup Community Area_70,Pickup Community Area_71,Pickup Community Area_72,Pickup Community Area_73,Pickup Community Area_74,Pickup Community Area_75,Pickup Community Area_76,Pickup Community Area_77
0,2019-06-24 00:00:00,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
1,2019-06-24 00:15:00,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
2,2019-06-24 00:30:00,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
3,2019-06-24 00:45:00,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
4,2019-06-24 01:00:00,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,2019-06-30 22:45:00,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
668,2019-06-30 23:00:00,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
669,2019-06-30 23:15:00,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
670,2019-06-30 23:30:00,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
671,2019-06-30 23:45:00,4.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0

Fit Weighted Moving Averages

In [19]:
# transformed_train = train.copy()

window = 10
weights = np.arange(1, window + 1)

sma_mae = []
sma_series = pd.Series(index=areas)
for area in areas:

    values = transformed_train[area].tail(window)
    # avg_window = (transformed_train[area].tail(window) * weights).mean() # Fit using scaled values

    avg_window = np.average(values, weights=weights)
    inversed_avg = np.expm1(avg_window)
    sma_series[area] = inversed_avg # hold the inversed forecast for each area
    forecast = np.ones(len(val)) * inversed_avg # just create val size of the sca
    sma_mae.append(mean_absolute_error(forecast, val[area]))


average_mae = np.array(sma_mae).mean()
print(f"average mean absolute error :{average_mae}")

average mean absolute error :0.839195618656573

In [20]:
sub_pred = pd.DataFrame(columns=sub_df.columns)
sub_pred['Trip Start Timestamp'] = sub_df['Trip Start Timestamp']

for area in areas:
    area_pred = np.ones(len(sub_df)) * sma_series[area]
    sub_pred[area] = area_pred

sub_pred

,Trip Start Timestamp,Pickup Community Area_0,Pickup Community Area_1,Pickup Community Area_2,Pickup Community Area_3,Pickup Community Area_4,Pickup Community Area_5,Pickup Community Area_6,Pickup Community Area_7,Pickup Community Area_8,...,Pickup Community Area_68,Pickup Community Area_69,Pickup Community Area_70,Pickup Community Area_71,Pickup Community Area_72,Pickup Community Area_73,Pickup Community Area_74,Pickup Community Area_75,Pickup Community Area_76,Pickup Community Area_77
0,2019-06-24 00:00:00,1.387096,0.206945,0.0,0.270864,0.078548,0.0,0.595988,0.461224,4.304777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400996,0.163267
1,2019-06-24 00:15:00,1.387096,0.206945,0.0,0.270864,0.078548,0.0,0.595988,0.461224,4.304777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400996,0.163267
2,2019-06-24 00:30:00,1.387096,0.206945,0.0,0.270864,0.078548,0.0,0.595988,0.461224,4.304777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400996,0.163267
3,2019-06-24 00:45:00,1.387096,0.206945,0.0,0.270864,0.078548,0.0,0.595988,0.461224,4.304777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400996,0.163267
4,2019-06-24 01:00:00,1.387096,0.206945,0.0,0.270864,0.078548,0.0,0.595988,0.461224,4.304777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400996,0.163267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,2019-06-30 22:45:00,1.387096,0.206945,0.0,0.270864,0.078548,0.0,0.595988,0.461224,4.304777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400996,0.163267
668,2019-06-30 23:00:00,1.387096,0.206945,0.0,0.270864,0.078548,0.0,0.595988,0.461224,4.304777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400996,0.163267
669,2019-06-30 23:15:00,1.387096,0.206945,0.0,0.270864,0.078548,0.0,0.595988,0.461224,4.304777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400996,0.163267
670,2019-06-30 23:30:00,1.387096,0.206945,0.0,0.270864,0.078548,0.0,0.595988,0.461224,4.304777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400996,0.163267
671,2019-06-30 23:45:00,1.387096,0.206945,0.0,0.270864,0.078548,0.0,0.595988,0.461224,4.304777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400996,0.163267

Simple Exponential Smoothing (SES)

Transform validation set

In [29]:
transformed_val = val.copy()
for area in areas:
    transformed_val[area] = np.log1p(transformed_val[area])

In [43]:
from statsmodels.tsa.holtwinters import SimpleExpSmoothing

sma_mae = []
val_models = {}   # models fit on train only (for validation scoring)
final_models = {} # models refit on train+val (for submission)


for area in areas:
    # --- Step 1: fit on train, validate ---
    y_train = transformed_train[area] + np.random.normal(0, 1e-8, size=len(transformed_train[area]))
    
    model = SimpleExpSmoothing(y_train, initialization_method="estimated")
    fit_model = model.fit(optimized=True)
    val_models[area] = fit_model

    val_forecast = fit_model.forecast(steps=len(val))
    val_forecast = np.expm1(val_forecast)
    sma_mae.append(mean_absolute_error(val[area], val_forecast))

    # --- Step 2: refit on train+val for the actual test/submission forecast ---
    y_full = pd.concat([transformed_train[area], val[area]])  # or however val is stored in log/transformed space
    y_full = y_full + np.random.normal(0, 1e-8, size=len(y_full))

    final_model = SimpleExpSmoothing(y_full, initialization_method="estimated")
    final_model = final_model.fit(optimized=True)
    final_models[area] = final_model

print("Average validation MAE:", np.mean(sma_mae))

Average validation MAE: 0.7571781430922346

Submission with Simple Exponential Model

In [46]:
sub_pred = pd.DataFrame(columns=sub_df.columns)
sub_pred['Trip Start Timestamp'] = sub_df['Trip Start Timestamp']

for area in areas:
    forecast = final_models[area].forecast(steps=len(sub_df))
    forecast = forecast
    sub_pred[area] = forecast.to_numpy()

sub_pred

,Trip Start Timestamp,Pickup Community Area_0,Pickup Community Area_1,Pickup Community Area_2,Pickup Community Area_3,Pickup Community Area_4,Pickup Community Area_5,Pickup Community Area_6,Pickup Community Area_7,Pickup Community Area_8,...,Pickup Community Area_68,Pickup Community Area_69,Pickup Community Area_70,Pickup Community Area_71,Pickup Community Area_72,Pickup Community Area_73,Pickup Community Area_74,Pickup Community Area_75,Pickup Community Area_76,Pickup Community Area_77
0,2019-06-24 00:00:00,3.897937,0.502423,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289062,0.090059
1,2019-06-24 00:15:00,3.897937,0.502423,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289062,0.090059
2,2019-06-24 00:30:00,3.897937,0.502423,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289062,0.090059
3,2019-06-24 00:45:00,3.897937,0.502423,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289062,0.090059
4,2019-06-24 01:00:00,3.897937,0.502423,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289062,0.090059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,2019-06-30 22:45:00,3.897937,0.502423,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289062,0.090059
668,2019-06-30 23:00:00,3.897937,0.502423,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289062,0.090059
669,2019-06-30 23:15:00,3.897937,0.502423,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289062,0.090059
670,2019-06-30 23:30:00,3.897937,0.502423,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289062,0.090059
671,2019-06-30 23:45:00,3.897937,0.502423,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289062,0.090059

Double Exponential Smoothing (Holt's Linear Trend)

In [47]:
from statsmodels.tsa.holtwinters import Holt

sma_mae = []
val_models = {}   # models fit on train only (for validation scoring)
final_models = {} # models refit on train+val (for submission)


for area in areas:
    # --- Step 1: fit on train, validate ---
    y_train = transformed_train[area] + np.random.normal(0, 1e-8, size=len(transformed_train[area]))
    
    model = Holt(y_train, initialization_method="estimated")
    fit_model = model.fit(optimized=True)
    val_models[area] = fit_model

    val_forecast = fit_model.forecast(steps=len(val))
    val_forecast = np.expm1(val_forecast)
    sma_mae.append(mean_absolute_error(val[area], val_forecast))

    # --- Step 2: refit on train+val for the actual test/submission forecast ---
    y_full = pd.concat([transformed_train[area], val[area]])  # or however val is stored in log/transformed space
    y_full = y_full + np.random.normal(0, 1e-8, size=len(y_full))

    final_model = SimpleExpSmoothing(y_full, initialization_method="estimated")
    final_model = final_model.fit(optimized=True)
    final_models[area] = final_model

print("Average validation MAE:", np.mean(sma_mae))

Average validation MAE: 1.7856334186237767e+38

Submission with Holt Model

In [ ]:
sub_pred = pd.DataFrame(columns=sub_df.columns)
sub_pred['Trip Start Timestamp'] = sub_df['Trip Start Timestamp']

for area in areas:
    forecast = final_models[area].forecast(steps=len(sub_df))
    forecast = forecast
    sub_pred[area] = forecast.to_numpy()

sub_pred

In [ ]:
Triple Exponential Smoothing (Holt-Winters)

In [49]:
from statsmodels.tsa.holtwinters import ExponentialSmoothing

sma_mae = []
val_models = {}   # models fit on train only (for validation scoring)
final_models = {} # models refit on train+val (for submission)


for area in areas:
    # --- Step 1: fit on train, validate ---
    y_train = transformed_train[area] + np.random.normal(0, 1e-8, size=len(transformed_train[area]))
    
    model = ExponentialSmoothing(y_train, initialization_method="estimated")
    fit_model = model.fit(optimized=True)
    val_models[area] = fit_model

    val_forecast = fit_model.forecast(steps=len(val))
    val_forecast = np.expm1(val_forecast)
    sma_mae.append(mean_absolute_error(val[area], val_forecast))

    # --- Step 2: refit on train+val for the actual test/submission forecast ---
    y_full = pd.concat([transformed_train[area], val[area]])  # or however val is stored in log/transformed space
    y_full = y_full + np.random.normal(0, 1e-8, size=len(y_full))

    final_model = SimpleExpSmoothing(y_full, initialization_method="estimated")
    final_model = final_model.fit(optimized=True)
    final_models[area] = final_model

print("Average validation MAE:", np.mean(sma_mae))

Average validation MAE: 0.7571781358048353

Submisstion with Holt-winters

In [50]:
sub_pred = pd.DataFrame(columns=sub_df.columns)
sub_pred['Trip Start Timestamp'] = sub_df['Trip Start Timestamp']

for area in areas:
    forecast = final_models[area].forecast(steps=len(sub_df))
    forecast = forecast
    sub_pred[area] = forecast.to_numpy()

sub_pred

,Trip Start Timestamp,Pickup Community Area_0,Pickup Community Area_1,Pickup Community Area_2,Pickup Community Area_3,Pickup Community Area_4,Pickup Community Area_5,Pickup Community Area_6,Pickup Community Area_7,Pickup Community Area_8,...,Pickup Community Area_68,Pickup Community Area_69,Pickup Community Area_70,Pickup Community Area_71,Pickup Community Area_72,Pickup Community Area_73,Pickup Community Area_74,Pickup Community Area_75,Pickup Community Area_76,Pickup Community Area_77
0,2019-06-24 00:00:00,3.897937,0.502415,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289063,0.090059
1,2019-06-24 00:15:00,3.897937,0.502415,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289063,0.090059
2,2019-06-24 00:30:00,3.897937,0.502415,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289063,0.090059
3,2019-06-24 00:45:00,3.897937,0.502415,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289063,0.090059
4,2019-06-24 01:00:00,3.897937,0.502415,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289063,0.090059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,2019-06-30 22:45:00,3.897937,0.502415,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289063,0.090059
668,2019-06-30 23:00:00,3.897937,0.502415,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289063,0.090059
669,2019-06-30 23:15:00,3.897937,0.502415,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289063,0.090059
670,2019-06-30 23:30:00,3.897937,0.502415,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289063,0.090059
671,2019-06-30 23:45:00,3.897937,0.502415,0.257196,0.292226,0.004102,0.087128,2.790172,0.605197,6.822294,...,0.025825,0.086172,0.000026,0.014917,0.003017,0.006723,0.00129,0.009731,15.289063,0.090059

Fit and Select Best SARIMA models Based on AIC

In [15]:
import pmdarima as pm

sarima_models = {}

for area in areas:
    print(f"Fit SARIMA model for {area}...")
    model = pm.auto_arima(
        transformed_train[area],
        seasonal=False,
    
        start_p=0,
        start_q=0,
        max_p=3,
        max_q=3,
    
        d=None,
        max_d=2,
    
        information_criterion="aic",
    
        stepwise=False,
        n_jobs=-1,
    
        error_action="ignore",
        suppress_warnings=True,
        trace=True
    )
    sarima_models[area] = model

Fit SARIMA model for Pickup Community Area_0...

Best model:  ARIMA(1,1,3)(0,0,0)[0] intercept
Total fit time: 4.814 seconds
Fit SARIMA model for Pickup Community Area_1...

Best model:  ARIMA(1,1,2)(0,0,0)[0] intercept
Total fit time: 5.847 seconds
Fit SARIMA model for Pickup Community Area_2...

Best model:  ARIMA(2,1,2)(0,0,0)[0] intercept
Total fit time: 4.512 seconds
Fit SARIMA model for Pickup Community Area_3...

Best model:  ARIMA(3,1,2)(0,0,0)[0] intercept
Total fit time: 4.974 seconds
Fit SARIMA model for Pickup Community Area_4...

Best model:  ARIMA(1,1,1)(0,0,0)[0] intercept
Total fit time: 4.921 seconds
Fit SARIMA model for Pickup Community Area_5...

Best model:  ARIMA(1,1,2)(0,0,0)[0] intercept
Total fit time: 5.516 seconds
Fit SARIMA model for Pickup Community Area_6...

Best model:  ARIMA(2,1,3)(0,0,0)[0] intercept
Total fit time: 5.932 seconds
Fit SARIMA model for Pickup Community Area_7...

Best model:  ARIMA(2,1,2)(0,0,0)[0] intercept
Total fit time: 4.986 seconds
Fit SARIMA model for Pickup Community Area_8...

Best model:  ARIMA(3,1,2)(0,0,0)[0] intercept
Total fit time: 5.079 seconds
Fit SARIMA model for Pickup Community Area_9...

Best model:  ARIMA(0,0,3)(0,0,0)[0]
Total fit time: 1.390 seconds
Fit SARIMA model for Pickup Community Area_10...

Best model:  ARIMA(1,1,1)(0,0,0)[0] intercept
Total fit time: 4.548 seconds
Fit SARIMA model for Pickup Community Area_11...

Best model:  ARIMA(0,1,1)(0,0,0)[0] intercept
Total fit time: 3.330 seconds
Fit SARIMA model for Pickup Community Area_12...

Best model:  ARIMA(3,1,1)(0,0,0)[0] intercept
Total fit time: 6.578 seconds
Fit SARIMA model for Pickup Community Area_13...

Best model:  ARIMA(1,1,1)(0,0,0)[0] intercept
Total fit time: 6.453 seconds
Fit SARIMA model for Pickup Community Area_14...

Best model:  ARIMA(3,1,1)(0,0,0)[0] intercept
Total fit time: 4.955 seconds
Fit SARIMA model for Pickup Community Area_15...

Best model:  ARIMA(1,1,3)(0,0,0)[0] intercept
Total fit time: 5.742 seconds
Fit SARIMA model for Pickup Community Area_16...

Best model:  ARIMA(3,1,1)(0,0,0)[0] intercept
Total fit time: 5.707 seconds
Fit SARIMA model for Pickup Community Area_17...

Best model:  ARIMA(3,1,1)(0,0,0)[0] intercept
Total fit time: 6.612 seconds
Fit SARIMA model for Pickup Community Area_18...

Best model:  ARIMA(3,1,2)(0,0,0)[0] intercept
Total fit time: 7.402 seconds
Fit SARIMA model for Pickup Community Area_19...

Best model:  ARIMA(0,1,1)(0,0,0)[0] intercept
Total fit time: 7.097 seconds
Fit SARIMA model for Pickup Community Area_20...

Best model:  ARIMA(2,1,3)(0,0,0)[0] intercept
Total fit time: 8.069 seconds
Fit SARIMA model for Pickup Community Area_21...

Best model:  ARIMA(1,1,2)(0,0,0)[0] intercept
Total fit time: 4.639 seconds
Fit SARIMA model for Pickup Community Area_22...

Best model:  ARIMA(3,1,1)(0,0,0)[0] intercept
Total fit time: 5.096 seconds
Fit SARIMA model for Pickup Community Area_23...

Best model:  ARIMA(1,1,2)(0,0,0)[0] intercept
Total fit time: 7.102 seconds
Fit SARIMA model for Pickup Community Area_24...

Best model:  ARIMA(1,1,3)(0,0,0)[0] intercept
Total fit time: 4.664 seconds
Fit SARIMA model for Pickup Community Area_25...

Best model:  ARIMA(1,1,1)(0,0,0)[0] intercept
Total fit time: 6.248 seconds
Fit SARIMA model for Pickup Community Area_26...

Best model:  ARIMA(1,0,0)(0,0,0)[0]
Total fit time: 1.396 seconds
Fit SARIMA model for Pickup Community Area_27...

Best model:  ARIMA(2,1,1)(0,0,0)[0] intercept
Total fit time: 7.511 seconds
Fit SARIMA model for Pickup Community Area_28...

Best model:  ARIMA(1,1,3)(0,0,0)[0] intercept
Total fit time: 4.027 seconds
Fit SARIMA model for Pickup Community Area_29...

Best model:  ARIMA(0,1,1)(0,0,0)[0] intercept
Total fit time: 6.502 seconds
Fit SARIMA model for Pickup Community Area_30...

Best model:  ARIMA(2,1,3)(0,0,0)[0] intercept
Total fit time: 9.285 seconds
Fit SARIMA model for Pickup Community Area_31...

Best model:  ARIMA(3,1,1)(0,0,0)[0] intercept
Total fit time: 6.492 seconds
Fit SARIMA model for Pickup Community Area_32...

Best model:  ARIMA(1,1,3)(0,0,0)[0] intercept
Total fit time: 4.738 seconds
Fit SARIMA model for Pickup Community Area_33...

Best model:  ARIMA(1,1,2)(0,0,0)[0] intercept
Total fit time: 4.872 seconds
Fit SARIMA model for Pickup Community Area_34...

Best model:  ARIMA(1,1,3)(0,0,0)[0] intercept
Total fit time: 5.503 seconds
Fit SARIMA model for Pickup Community Area_35...

Best model:  ARIMA(0,1,2)(0,0,0)[0] intercept
Total fit time: 3.710 seconds
Fit SARIMA model for Pickup Community Area_36...

Best model:  ARIMA(0,1,1)(0,0,0)[0] intercept
Total fit time: 7.902 seconds
Fit SARIMA model for Pickup Community Area_37...

Best model:  ARIMA(1,1,1)(0,0,0)[0] intercept
Total fit time: 9.033 seconds
Fit SARIMA model for Pickup Community Area_38...

Best model:  ARIMA(0,1,2)(0,0,0)[0] intercept
Total fit time: 6.523 seconds
Fit SARIMA model for Pickup Community Area_39...

Best model:  ARIMA(0,1,1)(0,0,0)[0] intercept
Total fit time: 4.188 seconds
Fit SARIMA model for Pickup Community Area_40...

Best model:  ARIMA(3,1,2)(0,0,0)[0] intercept
Total fit time: 7.463 seconds
Fit SARIMA model for Pickup Community Area_41...

Best model:  ARIMA(1,1,3)(0,0,0)[0] intercept
Total fit time: 5.162 seconds
Fit SARIMA model for Pickup Community Area_42...

Best model:  ARIMA(2,1,3)(0,0,0)[0] intercept
Total fit time: 4.583 seconds
Fit SARIMA model for Pickup Community Area_43...

Best model:  ARIMA(1,1,1)(0,0,0)[0] intercept
Total fit time: 4.833 seconds
Fit SARIMA model for Pickup Community Area_44...

Best model:  ARIMA(0,1,2)(0,0,0)[0] intercept
Total fit time: 5.399 seconds
Fit SARIMA model for Pickup Community Area_45...

Best model:  ARIMA(3,1,2)(0,0,0)[0] intercept
Total fit time: 7.115 seconds
Fit SARIMA model for Pickup Community Area_46...

Best model:  ARIMA(0,1,2)(0,0,0)[0] intercept
Total fit time: 5.658 seconds
Fit SARIMA model for Pickup Community Area_47...

Best model:  ARIMA(2,1,2)(0,0,0)[0] intercept
Total fit time: 8.439 seconds
Fit SARIMA model for Pickup Community Area_48...

Best model:  ARIMA(0,1,2)(0,0,0)[0] intercept
Total fit time: 5.661 seconds
Fit SARIMA model for Pickup Community Area_49...

Best model:  ARIMA(1,1,1)(0,0,0)[0] intercept
Total fit time: 4.566 seconds
Fit SARIMA model for Pickup Community Area_50...

Best model:  ARIMA(3,1,0)(0,0,0)[0] intercept
Total fit time: 8.134 seconds
Fit SARIMA model for Pickup Community Area_51...

Best model:  ARIMA(2,1,3)(0,0,0)[0] intercept
Total fit time: 7.337 seconds
Fit SARIMA model for Pickup Community Area_52...

Best model:  ARIMA(0,0,0)(0,0,0)[0]
Total fit time: 1.622 seconds
Fit SARIMA model for Pickup Community Area_53...

Best model:  ARIMA(0,1,2)(0,0,0)[0] intercept
Total fit time: 5.377 seconds
Fit SARIMA model for Pickup Community Area_54...

Best model:  ARIMA(2,1,3)(0,0,0)[0] intercept
Total fit time: 7.763 seconds
Fit SARIMA model for Pickup Community Area_55...

/home/isel-har/Documents/uber/.venv/lib/python3.11/site-packages/pmdarima/arima/auto.py:444: UserWarning: Input time-series is completely constant; returning a (0, 0, 0) ARMA.
  warnings.warn('Input time-series is completely constant; '

 ARIMA(0,0,0)(0,0,0)[0]             : AIC=-136681.619, Time=0.24 sec
Total fit time: 0.238 seconds
Fit SARIMA model for Pickup Community Area_56...

Best model:  ARIMA(2,1,2)(0,0,0)[0] intercept
Total fit time: 5.635 seconds
Fit SARIMA model for Pickup Community Area_57...

Best model:  ARIMA(0,0,1)(0,0,0)[0]
Total fit time: 1.425 seconds
Fit SARIMA model for Pickup Community Area_58...

Best model:  ARIMA(2,1,3)(0,0,0)[0] intercept
Total fit time: 10.003 seconds
Fit SARIMA model for Pickup Community Area_59...

Best model:  ARIMA(1,1,3)(0,0,0)[0] intercept
Total fit time: 3.483 seconds
Fit SARIMA model for Pickup Community Area_60...

Best model:  ARIMA(0,1,1)(0,0,0)[0] intercept
Total fit time: 8.371 seconds
Fit SARIMA model for Pickup Community Area_61...

Best model:  ARIMA(3,1,1)(0,0,0)[0] intercept
Total fit time: 8.435 seconds
Fit SARIMA model for Pickup Community Area_62...

Best model:  ARIMA(0,0,0)(0,0,0)[0]
Total fit time: 1.577 seconds
Fit SARIMA model for Pickup Community Area_63...

Best model:  ARIMA(3,1,0)(0,0,0)[0] intercept
Total fit time: 7.722 seconds
Fit SARIMA model for Pickup Community Area_64...

Best model:  ARIMA(0,0,1)(0,0,0)[0]
Total fit time: 1.598 seconds
Fit SARIMA model for Pickup Community Area_65...

Best model:  ARIMA(2,1,1)(0,0,0)[0] intercept
Total fit time: 7.669 seconds
Fit SARIMA model for Pickup Community Area_66...

Best model:  ARIMA(0,1,3)(0,0,0)[0] intercept
Total fit time: 8.360 seconds
Fit SARIMA model for Pickup Community Area_67...

Best model:  ARIMA(3,1,1)(0,0,0)[0] intercept
Total fit time: 7.015 seconds
Fit SARIMA model for Pickup Community Area_68...

Best model:  ARIMA(2,1,2)(0,0,0)[0] intercept
Total fit time: 6.741 seconds
Fit SARIMA model for Pickup Community Area_69...

Best model:  ARIMA(1,1,1)(0,0,0)[0] intercept
Total fit time: 4.981 seconds
Fit SARIMA model for Pickup Community Area_70...

Best model:  ARIMA(0,1,2)(0,0,0)[0] intercept
Total fit time: 7.881 seconds
Fit SARIMA model for Pickup Community Area_71...

Best model:  ARIMA(0,1,2)(0,0,0)[0] intercept
Total fit time: 5.220 seconds
Fit SARIMA model for Pickup Community Area_72...

Best model:  ARIMA(1,1,1)(0,0,0)[0] intercept
Total fit time: 7.491 seconds
Fit SARIMA model for Pickup Community Area_73...

Best model:  ARIMA(2,1,3)(0,0,0)[0] intercept
Total fit time: 7.553 seconds
Fit SARIMA model for Pickup Community Area_74...

/home/isel-har/Documents/uber/.venv/lib/python3.11/site-packages/pmdarima/arima/auto.py:444: UserWarning: Input time-series is completely constant; returning a (0, 0, 0) ARMA.
  warnings.warn('Input time-series is completely constant; '

 ARIMA(0,0,0)(0,0,0)[0]             : AIC=-136681.619, Time=0.21 sec
Total fit time: 0.212 seconds
Fit SARIMA model for Pickup Community Area_75...

Best model:  ARIMA(0,1,1)(0,0,0)[0] intercept
Total fit time: 8.800 seconds
Fit SARIMA model for Pickup Community Area_76...

Best model:  ARIMA(2,1,2)(0,0,0)[0] intercept
Total fit time: 4.373 seconds
Fit SARIMA model for Pickup Community Area_77...

Best model:  ARIMA(3,1,2)(0,0,0)[0] intercept
Total fit time: 5.331 seconds
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=1885.108, Time=2.53 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=1436.911, Time=2.27 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=9140.305, Time=1.61 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=8854.820, Time=2.18 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=8840.248, Time=4.89 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=7782.963, Time=4.83 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=6615.410, Time=3.96 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=7652.435, Time=0.58 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=7455.252, Time=3.68 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=7920.424, Time=3.19 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=1460.800, Time=1.82 sec
 ARIMA(1,0,1)(0,0,0)[0]             : AIC=-28829.419, Time=0.52 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=1957.218, Time=1.78 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=6807.681, Time=1.27 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-1966.009, Time=2.46 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=1931.734, Time=2.01 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=6721.779, Time=2.20 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=5473.942, Time=2.98 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=8019.315, Time=2.49 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=293.990, Time=0.77 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=5.37 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=6.53 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=1179.225, Time=0.48 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=5.91 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=6.20 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=7773.846, Time=0.57 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=6719.096, Time=2.72 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=9339.245, Time=0.49 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=8410.544, Time=2.27 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=5.28 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=8953.468, Time=1.17 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=1051.054, Time=2.07 sec
 ARIMA(0,0,2)(0,0,0)[0]             : AIC=-21043.042, Time=0.97 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=4.32 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=8640.478, Time=1.04 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-2542.059, Time=1.61 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-12259.474, Time=3.55 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=779.467, Time=2.25 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=5031.041, Time=0.65 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=9753.006, Time=0.86 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=7831.161, Time=3.93 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=5318.493, Time=2.13 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=7165.022, Time=0.59 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=6386.755, Time=2.35 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=5.16 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=-15088.045, Time=4.45 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=1507.051, Time=3.92 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=3977.285, Time=2.10 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=-11582.408, Time=1.16 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=5.81 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=6526.516, Time=4.79 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=478.490, Time=2.85 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=2298.268, Time=1.99 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=1064.967, Time=2.36 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=-11338.796, Time=2.53 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=1555.062, Time=0.57 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-1345.294, Time=0.60 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=-3275.343, Time=0.54 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-5999.651, Time=1.33 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=15.006, Time=0.71 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-2646.980, Time=0.62 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=-3718.873, Time=3.93 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=209.873, Time=3.17 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=4.88 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=-2444.566, Time=0.77 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=6.06 sec
 ARIMA(2,0,1)(0,0,0)[0]             : AIC=-30914.715, Time=1.34 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=-2354.217, Time=3.23 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=-26968.112, Time=0.70 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=-29353.945, Time=4.76 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=9500.495, Time=2.49 sec
 ARIMA(1,0,3)(0,0,0)[0]             : AIC=-28610.137, Time=0.75 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=6.21 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=3328.703, Time=2.70 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=12.548, Time=0.50 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-370.249, Time=0.60 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=-8554.296, Time=0.96 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=-11174.016, Time=4.69 sec
 ARIMA(1,0,1)(0,0,0)[0]             : AIC=-27534.892, Time=0.44 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=4.56 sec
 ARIMA(0,0,3)(0,0,0)[0]             : AIC=-30182.106, Time=1.36 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=-21508.766, Time=6.01 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=5.16 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=5.34 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=5.07 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=-959.003, Time=2.20 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=-11500.684, Time=3.83 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=-848.703, Time=2.20 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=-19926.769, Time=3.23 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=-1731.268, Time=3.12 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=5.00 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=7489.577, Time=1.32 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=10126.035, Time=0.37 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=9248.240, Time=0.60 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=1885.990, Time=2.89 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=1368.845, Time=3.15 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=9105.612, Time=3.70 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=8854.822, Time=1.91 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=8849.477, Time=1.72 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=7777.229, Time=3.46 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=6613.386, Time=4.57 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=7472.738, Time=1.51 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=7981.710, Time=1.23 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=1516.788, Time=0.70 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=1123.507, Time=4.29 sec
 ARIMA(2,0,3)(0,0,0)[0]             : AIC=-28904.540, Time=0.80 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=3844.320, Time=0.36 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=2828.132, Time=0.83 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=10582.527, Time=0.50 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=6812.233, Time=2.76 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=-1965.753, Time=5.98 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=1885.108, Time=2.52 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=8732.255, Time=0.45 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=7634.875, Time=0.69 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=8966.712, Time=0.57 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=5475.956, Time=3.62 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=8016.798, Time=2.97 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=-397.978, Time=0.50 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-833.581, Time=0.60 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=-5014.269, Time=0.54 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-7994.176, Time=2.23 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-468.768, Time=2.32 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-15769.057, Time=2.78 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=6725.440, Time=1.40 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=8411.132, Time=0.81 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=4755.140, Time=0.52 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=5.39 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=8951.511, Time=2.51 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=1055.028, Time=4.47 sec
 ARIMA(2,0,0)(0,0,0)[0]             : AIC=-21042.822, Time=0.40 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=3020.705, Time=0.51 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=617.624, Time=0.63 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=9696.280, Time=0.57 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=8216.309, Time=3.38 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=-2539.273, Time=6.41 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=-12315.608, Time=9.20 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=783.208, Time=4.86 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=4459.550, Time=2.90 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=8043.859, Time=0.41 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=7967.119, Time=0.60 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=8036.971, Time=0.82 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=5310.525, Time=1.88 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=6382.900, Time=2.39 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=4.45 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=-15057.704, Time=7.10 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=1506.933, Time=2.66 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=5564.561, Time=0.37 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=4588.175, Time=0.68 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=-10221.508, Time=0.52 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-12486.335, Time=1.87 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=9433.594, Time=0.53 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=6568.192, Time=1.87 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=479.532, Time=4.21 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=2287.049, Time=2.63 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=1064.995, Time=2.48 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=-13280.030, Time=3.23 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-2350.126, Time=1.94 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=-6988.654, Time=4.86 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=-3722.807, Time=2.34 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=208.767, Time=1.92 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=3.66 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-4318.795, Time=1.86 sec
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=-30920.716, Time=0.31 sec
 ARIMA(3,0,1)(0,0,0)[0]             : AIC=-30912.715, Time=0.60 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=-434.708, Time=0.76 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=-2356.087, Time=4.09 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=-29458.203, Time=7.10 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=9386.140, Time=3.51 sec
 ARIMA(2,0,1)(0,0,0)[0]             : AIC=-28612.137, Time=0.58 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=3.91 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=4371.290, Time=0.75 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=3332.409, Time=2.07 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=5.48 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=8.34 sec
 ARIMA(2,0,3)(0,0,0)[0]             : AIC=-27528.893, Time=0.98 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=-18514.323, Time=0.96 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=6.47 sec
 ARIMA(2,0,2)(0,0,0)[0]             : AIC=-30180.106, Time=0.59 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-21486.843, Time=2.78 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=-11091.509, Time=0.92 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-12775.715, Time=2.44 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-13196.656, Time=2.79 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-4117.665, Time=2.43 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=-955.813, Time=3.30 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=6.13 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=1270.704, Time=0.95 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=-842.922, Time=3.83 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=5.35 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=4.36 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=-4820.763, Time=2.47 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=6.24 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=7353.667, Time=4.22 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=8828.992, Time=1.55 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=1885.780, Time=2.75 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=1738.152, Time=0.82 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=12393.974, Time=0.58 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=9137.520, Time=3.09 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=8850.188, Time=3.28 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=8846.437, Time=1.99 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=7780.855, Time=2.15 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=6611.419, Time=4.90 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=7455.550, Time=2.85 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=7921.206, Time=2.91 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=1459.197, Time=0.85 sec
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=-28833.419, Time=0.33 sec
 ARIMA(3,0,2)(0,0,0)[0]             : AIC=-28903.520, Time=0.80 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=3237.499, Time=0.49 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=1931.829, Time=2.93 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=7992.123, Time=0.57 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=6814.132, Time=2.30 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=-1984.751, Time=4.40 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=4.62 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=7994.039, Time=0.57 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=6703.475, Time=4.31 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=5469.252, Time=5.25 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=8015.563, Time=2.84 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=5.28 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=5.19 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=3.59 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=3.79 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=6716.268, Time=2.25 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=9970.247, Time=0.37 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=8925.111, Time=0.72 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=2.88 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=8951.817, Time=0.87 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=4664.596, Time=0.55 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=5.63 sec
 ARIMA(2,0,3)(0,0,0)[0]             : AIC=-21037.042, Time=0.82 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=-314.058, Time=4.51 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=8266.474, Time=2.01 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=-2539.852, Time=4.30 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=-9924.474, Time=0.94 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=7.48 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=749.178, Time=5.35 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=4976.808, Time=1.62 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=7996.125, Time=1.12 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=5312.262, Time=1.52 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=6380.941, Time=1.30 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=3.43 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=-15088.023, Time=4.04 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=1506.482, Time=1.76 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=3971.608, Time=1.09 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=3.14 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=6595.725, Time=1.76 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=476.085, Time=2.37 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=2287.254, Time=2.91 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=1068.312, Time=5.25 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=6.66 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=-2346.619, Time=4.41 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=5.70 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=-3719.419, Time=3.22 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=208.248, Time=3.29 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=8.06 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=-4391.595, Time=6.90 sec
 ARIMA(2,0,2)(0,0,0)[0]             : AIC=-30912.715, Time=1.59 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=-2354.325, Time=5.29 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=-29516.052, Time=5.50 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=9393.122, Time=2.86 sec
 ARIMA(2,0,0)(0,0,0)[0]             : AIC=-28614.137, Time=0.27 sec
 ARIMA(3,0,1)(0,0,0)[0]             : AIC=-28610.137, Time=0.77 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=-15372.111, Time=2.36 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=7.55 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=3332.359, Time=2.05 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=-1529.693, Time=4.66 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=-9540.656, Time=0.71 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=-10258.017, Time=1.18 sec
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=-27538.893, Time=0.25 sec
 ARIMA(3,0,1)(0,0,0)[0]             : AIC=-27530.892, Time=0.74 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=5.59 sec
 ARIMA(1,0,0)(0,0,0)[0]             : AIC=-30185.842, Time=0.28 sec
 ARIMA(3,0,1)(0,0,0)[0]             : AIC=-30180.106, Time=0.78 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=-21504.018, Time=4.58 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=-13921.906, Time=6.54 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=4.69 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=5.70 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=420.839, Time=0.50 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=12.167, Time=0.61 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=-8669.812, Time=0.81 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=5.77 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=-845.443, Time=3.08 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=-19815.481, Time=4.68 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=4.70 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=-6963.682, Time=3.73 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=7489.320, Time=0.93 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=8827.256, Time=1.62 sec
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=1888.160, Time=3.60 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=1368.031, Time=3.46 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=10045.560, Time=0.52 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=9125.260, Time=2.29 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=9800.506, Time=0.53 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=8856.751, Time=2.05 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=9438.715, Time=0.50 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=8841.684, Time=1.75 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=8830.452, Time=0.57 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=7780.213, Time=2.03 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=6615.703, Time=3.46 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=7462.411, Time=3.17 sec

compute the average of mean absolute error of best SARIMA Model for each Area

Forecast using best SARIMA models for each Area

In [21]:

sma_mae = []
sarima_forecasts = {}
for area in areas:
    forecast = sarima_models[area].predict(n_periods=len(val) + len(sub_df))
    forecast = np.expm1(forecast)
    sarima_forecasts[area] = forecast
    sma_mae.append(mean_absolute_error(forecast[:len(val)], val[area]))

mae_avg = np.array(sma_mae).mean()
print(f"Mean Absolute Error : {mae_avg}")

Mean Absolute Error : 0.8974713317877129

In [ ]:
Submit using ARIMA model

In [23]:
sub_pred = pd.DataFrame(columns=sub_df.columns)
sub_pred['Trip Start Timestamp'] = sub_df['Trip Start Timestamp']

for area in areas:

    forecast = sarima_forecasts[area][len(val):]
    sub_pred[area] = forecast.to_numpy()


sub_pred

,Trip Start Timestamp,Pickup Community Area_0,Pickup Community Area_1,Pickup Community Area_2,Pickup Community Area_3,Pickup Community Area_4,Pickup Community Area_5,Pickup Community Area_6,Pickup Community Area_7,Pickup Community Area_8,...,Pickup Community Area_68,Pickup Community Area_69,Pickup Community Area_70,Pickup Community Area_71,Pickup Community Area_72,Pickup Community Area_73,Pickup Community Area_74,Pickup Community Area_75,Pickup Community Area_76,Pickup Community Area_77
0,2019-06-24 00:00:00,5.859422,0.797973,0.027297,0.227984,0.062291,0.063829,-0.780979,0.694870,-0.400025,...,0.007227,-0.000864,-0.002688,-0.009304,-0.010063,0.007446,0.0,-0.015218,-0.408079,0.183048
1,2019-06-24 00:15:00,5.860911,0.798492,0.027297,0.227948,0.062295,0.063834,-0.781215,0.694968,-0.400608,...,0.007226,-0.000865,-0.002689,-0.009310,-0.010069,0.007442,0.0,-0.015227,-0.408194,0.183071
2,2019-06-24 00:30:00,5.862400,0.799012,0.027296,0.227911,0.062299,0.063840,-0.781452,0.695065,-0.401191,...,0.007225,-0.000865,-0.002691,-0.009316,-0.010075,0.007439,0.0,-0.015236,-0.408308,0.183095
3,2019-06-24 00:45:00,5.863890,0.799531,0.027296,0.227875,0.062303,0.063845,-0.781688,0.695163,-0.401773,...,0.007224,-0.000866,-0.002693,-0.009322,-0.010081,0.007436,0.0,-0.015245,-0.408423,0.183118
4,2019-06-24 01:00:00,5.865380,0.800050,0.027296,0.227839,0.062308,0.063850,-0.781924,0.695261,-0.402355,...,0.007223,-0.000866,-0.002694,-0.009327,-0.010086,0.007433,0.0,-0.015254,-0.408538,0.183141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,2019-06-30 22:45:00,6.928047,1.179648,0.027083,0.204087,0.064984,0.067275,-0.893514,0.761313,-0.686413,...,0.006556,-0.001221,-0.003755,-0.013129,-0.013965,0.005342,0.0,-0.021211,-0.479860,0.198658
668,2019-06-30 23:00:00,6.929768,1.180277,0.027083,0.204052,0.064988,0.067280,-0.893629,0.761415,-0.686718,...,0.006555,-0.001221,-0.003757,-0.013135,-0.013971,0.005339,0.0,-0.021220,-0.479961,0.198681
669,2019-06-30 23:15:00,6.931489,1.180907,0.027082,0.204016,0.064992,0.067286,-0.893744,0.761516,-0.687022,...,0.006554,-0.001222,-0.003758,-0.013141,-0.013977,0.005336,0.0,-0.021229,-0.480062,0.198705
670,2019-06-30 23:30:00,6.933211,1.181536,0.027082,0.203981,0.064996,0.067291,-0.893859,0.761618,-0.687327,...,0.006553,-0.001222,-0.003760,-0.013147,-0.013982,0.005333,0.0,-0.021238,-0.480162,0.198729
671,2019-06-30 23:45:00,6.934933,1.182166,0.027082,0.203945,0.065000,0.067296,-0.893973,0.761719,-0.687631,...,0.006552,-0.001223,-0.003761,-0.013152,-0.013988,0.005330,0.0,-0.021247,-0.480263,0.198752